apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: perpustakaan-ns
spec:
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: perpus/eureka-server:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: perpustakaan-ns
spec:
  ports:
  - port: 8761
  selector:
    app: eureka