apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-app
  namespace: perpustakaan-ns
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql-service"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: { name: perpus-secrets, key: mysql-root-password }
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: perpustakaan-ns
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: phpmyadmin